name = "image-api"
main = "src/index.ts"
compatibility_date = "2025-06-24"

[[routes]]
pattern = "cdn.karasu256.com"
custom_domain = true

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "karasu-lab-cdn"

[vars]
ALLOWED_ORIGIN = "https://karasu256.com"
FIREBASE_PROJECT_ID = "karasu-lab-application"
CDN_BASE_URL = "https://cdn.karasu256.com"

[env.dev]
routes = []

[[env.dev.r2_buckets]]
binding = "IMAGES"
bucket_name = "karasu-lab-cdn-dev"

[env.dev.vars]
ALLOWED_ORIGIN = "https://karasu256.com"
FIREBASE_PROJECT_ID = "karasu-lab-application"
CDN_BASE_URL = "http://localhost:8788"
