name = "image-api"
main = "src/index.ts"
compatibility_date = "2025-06-24"

[[routes]]
pattern = "cdn.karasu256.com"
custom_domain = true

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "karasu-lab-cdn"

[vars]
ALLOWED_ORIGIN = "https://karasu256.com"
FIREBASE_PROJECT_ID = "karasu-lab-application"
