packages:
  - 'apps/*'
  - 'packages/*'

overrides:
  jwks-rsa>jose: '^5.10.0'

allowBuilds:
  '@tailwindcss/oxide': true
  sharp: true
  unrs-resolver: true
  '@firebase/util': true
  protobufjs: true
  esbuild: true
  workerd: true
  '@swc/core': true
  simple-git-hooks: true
  core-js: true
  '@parcel/watcher': true
  cpu-features: true
  ssh2: true
