packages:
  - "."
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@tailwindcss/oxide": true
  sharp: true
  unrs-resolver: true
  "@firebase/util": true
  protobufjs: true
  esbuild: true
  workerd: true
  '@swc/core': true
  simple-git-hooks: true
