import type { Metadata } from 'next';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { PopUpMenuProvider, R2StorageProvider, SessionProvider } from '@Hashibutogarasu/ui';
import { RedisProvider } from '@Hashibutogarasu/ui/redis';
import { geistSans, geistMono, notoSansJP } from '@Hashibutogarasu/ui/fonts';
import { getSessionUser } from '@Hashibutogarasu/utils/server';
import './globals.css';
import Header from '@/components/Header';

config.autoAddCss = false;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  const sessionUser = await getSessionUser(process.env.NEXT_PUBLIC_ACCOUNTS_URL, process.env.VERCEL_PROTECTION_BYPASS_SECRET);
  const initialUser = sessionUser
    ? { uid: sessionUser.uid, iconUrl: sessionUser.image, displayName: sessionUser.name, email: sessionUser.email }
    : null;

  return (
    <html lang={locale} className={`${geistSans.variable} ${geistMono.variable} ${notoSansJP.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider messages={messages}>
          <SessionProvider baseURL={process.env.NEXT_PUBLIC_ACCOUNTS_URL} initialUser={initialUser}>
            <R2StorageProvider imageApiUrl={process.env.NEXT_PUBLIC_IMAGE_API_URL!}>
              <RedisProvider redisURL={process.env.REDIS_URL!}>
                <PopUpMenuProvider>
                  <Header />
                  <main className="flex-1 flex flex-col">{children}</main>
                </PopUpMenuProvider>
              </RedisProvider>
            </R2StorageProvider>
          </SessionProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
