import type { Metadata } from 'next';
import { Geist, Geist_Mono, Noto_Sans_JP } from 'next/font/google';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { PopUpMenuProvider, R2StorageProvider } from '@Hashibutogarasu/ui';
import { RedisProvider } from '@Hashibutogarasu/ui/redis';
import { getSessionUser } from '@Hashibutogarasu/utils/server';
import './globals.css';
import Header from '@/components/Header';
import { SessionRoot } from '@/components/SessionRoot';

config.autoAddCss = false;

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

/** CJK fallback so ja/cn glyphs render consistently with the Geist Latin text instead of the OS default font. */
const notoSansJP = Noto_Sans_JP({
  variable: '--font-noto-jp',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  const sessionUser = await getSessionUser();
  const initialUser = sessionUser
    ? { uid: sessionUser.uid, iconUrl: sessionUser.image, displayName: sessionUser.name, email: sessionUser.email }
    : null;

  return (
    <html lang={locale} className={`${geistSans.variable} ${geistMono.variable} ${notoSansJP.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider messages={messages}>
          <SessionRoot initialUser={initialUser}>
            <R2StorageProvider imageApiUrl={process.env.NEXT_PUBLIC_IMAGE_API_URL!}>
              <RedisProvider redisURL={process.env.REDIS_URL!}>
                <PopUpMenuProvider>
                  <Header />
                  <main className="flex-1 flex flex-col">{children}</main>
                </PopUpMenuProvider>
              </RedisProvider>
            </R2StorageProvider>
          </SessionRoot>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
