development:
  webauthn:
    rpId: localhost
    rpName: Karasu Lab
    expectedOrigins:
      - http://localhost:3001

production:
  webauthn:
    rpId: accounts.karasu256.com
    rpName: Karasu Lab
    expectedOrigins:
      - https://accounts.karasu256.com
