import type { NextConfig } from 'next';
import createNextIntlPlugin from 'next-intl/plugin';

const withNextIntl = createNextIntlPlugin('./src/i18n/request.ts');

const nextConfig: NextConfig = {
  transpilePackages: ['@Hashibutogarasu/ui', '@Hashibutogarasu/utils', '@Hashibutogarasu/flags'],
  devIndicators: false,
  /**
   * `@vercel/flags-core` dynamically imports the optional `@vercel/flags-definitions`
   * module (generated by the Vercel CLI at build time) and already handles it being
   * absent via a `MODULE_NOT_FOUND` catch. The dynamic import is only marked
   * `turbopackOptional`, which webpack does not understand, so webpack's build-time
   * bundling fails hard on the unresolved module. Excluding the package from
   * webpack's bundle defers its `require`/`import()` calls to the Node.js runtime,
   * where the existing fallback handling applies.
   */
  serverExternalPackages: ['@vercel/flags-core'],
  /** The OAuth client test in accounts' developer settings calls `/api/profile` cross-origin with a Bearer token. */
  async headers() {
    const accountsUrl = process.env.NEXT_PUBLIC_ACCOUNTS_URL;
    if (!accountsUrl) return [];
    return [
      {
        source: '/api/profile',
        headers: [
          { key: 'Access-Control-Allow-Origin', value: accountsUrl },
          { key: 'Access-Control-Allow-Methods', value: 'GET, PATCH, OPTIONS' },
          { key: 'Access-Control-Allow-Headers', value: 'Authorization, Content-Type' },
          { key: 'Vary', value: 'Origin' },
        ],
      },
    ];
  },
};

export default withNextIntl(nextConfig);
