name = "cron-jobs"
main = "src/index.ts"
compatibility_date = "2025-06-24"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 0 * * *"]

[vars]
QR_APP_URL = "https://qr.karasu256.com"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
