webauthn:
  rpId: karasu256.com
  expectedOrigins:
    - https://local-accounts.karasu256.com
    - https://local-auth.karasu256.com
    - android:apk-key-hash:bfKpYRlXNOkeRYJCoMaSQi9kSA6IKX4TYjuCHg35mws
    - android:apk-key-hash:uo795W5PTsfIrzRiahbhbBMqqve55APHGJ3H55qPlDk

trustedOrigins:
  - http://localhost:3000
  - http://localhost:3001
  - http://localhost:3002
  - http://localhost:3004
  - https://local.karasu256.com
  - https://local-accounts.karasu256.com
  - https://local-qr.karasu256.com
  - https://local-auth.karasu256.com
