webauthn:
  rpId: localhost
  expectedOrigins:
    - http://localhost:3001
    - http://localhost:3004

trustedOrigins:
  - http://localhost:3000
  - http://localhost:3001
  - http://localhost:3002
  - http://localhost:3004
